[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.60
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = true

[window.padding]
x = 15
y = 15

[keyboard]
bindings = [
{ key = "V", mods = "Control|Shift", action = "Paste" },
{ key = "C", mods = "Control|Shift", action = "Copy" }]
